// Generated by j.chamois
'use strict';

module.exports = function (grunt) {

    // charge les tache grunt en auto
    require('load-grunt-tasks')(grunt);

    // Config des taches
    grunt.initConfig({

        yeoman: {
            // chemin dossier projet
            app: 'app',
            dist: 'dist',
            css : 'src/css'
        },

        // Vide les rep précédemment remplit
        clean: {
            dist: {
                files: [{
                    dot: true,
                    src: [ '<%= yeoman.dist %>/']
                }]
            }
        },

        cssmin: {

          target: {
            files: [{
              expand: true,
              cwd: '<%= yeoman.app %>/<%= yeoman.css %>',
              src: ['*.css', '!*.min.css'],
              dest: 'dist/css',
              ext: '.min.css'
            }]
          }
        }


    });

    grunt.registerTask('build', [ // run grunt build
        'clean:dist',
        'cssmin'
    ]);

    grunt.registerTask('dev', [ // run grunt dev
        'clean:dist',
        'includes',
        'concurrent:dev'
    ]);

};
